[package]
name = "treedb"
version = "0.1.0"
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
lru = "0.4"
serde = { version = "1", features = ["derive"] }
bincode = "1"
zerocopy = "0.3"
bytes = "0.5"

[dev-dependencies]
tempfile = "3"